// Sample products data - 15 products across 6 categories
export const sampleProducts = [
  {
    id: 1,
    name: "Monstera Deliciosa",
    slug: "monstera-deliciosa",
    description:
      "A stunning tropical plant with large, glossy, heart-shaped leaves that develop natural splits as they mature. Perfect for adding a bold statement to any indoor space.",
    long_description:
      "The Monstera Deliciosa, also known as the Swiss Cheese Plant, is a popular choice for indoor gardening enthusiasts. Native to the rainforests of Central America, this plant thrives in bright, indirect light and moderate humidity. Its iconic split leaves make it a favorite for modern interior design.",
    price: 2499,
    category: "plants",
    colors: ["Green"],
    sizes: ["Small", "Medium", "Large"],
    stock: 25,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.8,
    reviews_count: 124,
    featured: true,
    additional_info: {
      light: "Bright, indirect light",
      water: "Water when top 2 inches of soil are dry",
      temperature: "18-27°C",
      humidity: "Medium to high",
      pet_friendly: false,
    },
  },
  {
    id: 2,
    name: "Snake Plant (Sansevieria)",
    slug: "snake-plant-sansevieria",
    description:
      "An incredibly hardy and low-maintenance plant with striking upright leaves. Excellent air purifier and perfect for beginners.",
    long_description:
      "The Snake Plant, also known as Mother-in-Law's Tongue, is one of the most resilient houseplants available. It can tolerate low light, irregular watering, and still thrive. NASA studies have shown it's excellent at removing toxins from the air.",
    price: 899,
    category: "plants",
    colors: ["Green", "Yellow-Green"],
    sizes: ["Small", "Medium"],
    stock: 40,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.9,
    reviews_count: 201,
    featured: true,
    additional_info: {
      light: "Low to bright, indirect light",
      water: "Water every 2-3 weeks",
      temperature: "15-29°C",
      humidity: "Low to medium",
      pet_friendly: false,
    },
  },
  {
    id: 3,
    name: "Tomato Seeds - Heirloom Variety",
    slug: "tomato-seeds-heirloom",
    description:
      "Premium heirloom tomato seeds producing large, flavorful fruits. Organic and non-GMO. Pack of 50 seeds.",
    long_description:
      "These heirloom tomato seeds are carefully selected for superior taste and productivity. Perfect for home gardeners looking to grow authentic, flavorful tomatoes. High germination rate guaranteed.",
    price: 299,
    category: "seeds",
    colors: ["N/A"],
    sizes: ["50 Seeds", "100 Seeds"],
    stock: 150,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.7,
    reviews_count: 89,
    featured: false,
    additional_info: {
      germination_time: "7-14 days",
      planting_depth: "0.5 cm",
      spacing: "60-90 cm",
      harvest_time: "60-80 days",
      organic: true,
    },
  },
  {
    id: 4,
    name: "Basil Seeds - Sweet Genovese",
    slug: "basil-seeds-sweet-genovese",
    description:
      "Aromatic sweet basil seeds perfect for culinary use. Easy to grow indoors or outdoors. Pack of 100 seeds.",
    long_description:
      "Sweet Genovese Basil is the classic Italian basil variety, perfect for pesto, salads, and Italian dishes. These seeds are easy to germinate and grow quickly, providing fresh herbs for your kitchen.",
    price: 199,
    category: "seeds",
    colors: ["N/A"],
    sizes: ["100 Seeds", "250 Seeds"],
    stock: 200,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.6,
    reviews_count: 156,
    featured: false,
    additional_info: {
      germination_time: "5-10 days",
      planting_depth: "0.25 cm",
      spacing: "15-30 cm",
      harvest_time: "30-40 days",
      organic: true,
    },
  },
  {
    id: 5,
    name: "Ceramic Planter - Modern White",
    slug: "ceramic-planter-modern-white",
    description:
      "Elegant white ceramic planter with drainage hole. Minimalist design perfect for any decor style.",
    long_description:
      "This handcrafted ceramic planter features a smooth matte finish and modern geometric design. The included drainage hole ensures proper water management. Comes with a matching saucer.",
    price: 1299,
    category: "planters",
    colors: ["White", "Grey", "Black"],
    sizes: ["Small (4 inch)", "Medium (6 inch)", "Large (8 inch)"],
    stock: 60,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.8,
    reviews_count: 98,
    featured: true,
    additional_info: {
      material: "Ceramic",
      drainage: "Yes",
      saucer_included: true,
      indoor_outdoor: "Indoor",
      weight: "500g - 1.2kg (varies by size)",
    },
  },
  {
    id: 6,
    name: "Terracotta Pot Set",
    slug: "terracotta-pot-set",
    description:
      "Classic terracotta pots in a set of 3. Natural clay material perfect for healthy plant growth.",
    long_description:
      "Traditional terracotta pots are ideal for plant health as they allow air and water to pass through the walls. This set includes three different sizes for various plant types. Each pot has a drainage hole.",
    price: 799,
    category: "planters",
    colors: ["Terracotta"],
    sizes: ["Set of 3"],
    stock: 35,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.5,
    reviews_count: 67,
    featured: false,
    additional_info: {
      material: "Natural Clay",
      drainage: "Yes",
      saucer_included: false,
      indoor_outdoor: "Both",
      sizes_included: "4 inch, 6 inch, 8 inch",
    },
  },
  {
    id: 7,
    name: "Organic Potting Mix - Premium Blend",
    slug: "organic-potting-mix-premium",
    description:
      "Nutrient-rich organic potting soil perfect for indoor and outdoor plants. 5kg bag.",
    long_description:
      "Our premium potting mix is specially formulated with coco peat, vermicompost, perlite, and organic nutrients. Provides excellent drainage while retaining moisture. pH balanced for optimal plant growth.",
    price: 449,
    category: "plant-care",
    colors: ["N/A"],
    sizes: ["5kg", "10kg", "20kg"],
    stock: 100,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.9,
    reviews_count: 234,
    featured: true,
    additional_info: {
      composition: "Coco Peat, Vermicompost, Perlite, Neem Cake",
      ph_level: "6.0-6.5",
      organic: true,
      suitable_for: "All plant types",
      shelf_life: "12 months",
    },
  },
  {
    id: 8,
    name: "Liquid Plant Food - All Purpose",
    slug: "liquid-plant-food-all-purpose",
    description:
      "Complete liquid fertilizer for healthy plant growth. NPK 10-10-10. 500ml concentrate.",
    long_description:
      "This all-purpose liquid plant food provides essential nutrients for vigorous growth, lush foliage, and abundant blooms. Easy to use - just dilute with water. Suitable for indoor and outdoor plants.",
    price: 349,
    category: "plant-care",
    colors: ["N/A"],
    sizes: ["500ml", "1L"],
    stock: 80,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.7,
    reviews_count: 145,
    featured: false,
    additional_info: {
      npk_ratio: "10-10-10",
      dilution_ratio: "5ml per liter of water",
      frequency: "Every 2 weeks during growing season",
      organic: false,
      shelf_life: "24 months",
    },
  },
  {
    id: 9,
    name: "Macrame Plant Hanger",
    slug: "macrame-plant-hanger",
    description:
      "Handwoven macrame plant hanger in natural cotton. Adds bohemian charm to any space.",
    long_description:
      "This beautiful macrame plant hanger is handcrafted from 100% natural cotton rope. Features intricate knotwork and can hold pots up to 8 inches in diameter. Perfect for creating vertical gardens.",
    price: 699,
    category: "decor",
    colors: ["Natural", "Black", "Cream"],
    sizes: ["36 inch", "48 inch"],
    stock: 45,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.8,
    reviews_count: 112,
    featured: false,
    additional_info: {
      material: "100% Cotton Rope",
      max_pot_diameter: "8 inches",
      weight_capacity: "5 kg",
      installation: "Ceiling hook included",
      handmade: true,
    },
  },
  {
    id: 10,
    name: "Plant Stand - Bamboo",
    slug: "plant-stand-bamboo",
    description:
      "Sustainable bamboo plant stand with 3 tiers. Elegant display for multiple plants.",
    long_description:
      "This eco-friendly bamboo plant stand features three spacious shelves perfect for creating a stunning plant display. Made from sustainable bamboo with a natural finish. Easy assembly required.",
    price: 1899,
    category: "decor",
    colors: ["Natural Bamboo"],
    sizes: ["3 Tier"],
    stock: 20,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.6,
    reviews_count: 78,
    featured: true,
    additional_info: {
      material: "Sustainable Bamboo",
      dimensions: "80cm H x 60cm W x 25cm D",
      weight_capacity: "15 kg total",
      assembly_required: true,
      eco_friendly: true,
    },
  },
  {
    id: 11,
    name: "Pruning Shears - Professional",
    slug: "pruning-shears-professional",
    description:
      "Sharp stainless steel pruning shears with ergonomic grip. Perfect for precise cuts.",
    long_description:
      "These professional-grade pruning shears feature ultra-sharp stainless steel blades that stay sharp longer. The ergonomic non-slip grip reduces hand fatigue. Includes a safety lock and cleaning cloth.",
    price: 899,
    category: "accessories",
    colors: ["Green/Silver", "Black/Silver"],
    sizes: ["8 inch"],
    stock: 70,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.9,
    reviews_count: 189,
    featured: false,
    additional_info: {
      blade_material: "Stainless Steel",
      handle_material: "Rubberized Grip",
      cutting_capacity: "Up to 20mm diameter",
      warranty: "1 year",
      includes: "Safety lock, cleaning cloth",
    },
  },
  {
    id: 12,
    name: "Watering Can - Vintage Style",
    slug: "watering-can-vintage-style",
    description:
      "Charming vintage-style metal watering can with removable rose sprinkler. 1.5L capacity.",
    long_description:
      "This beautifully designed watering can combines functionality with vintage aesthetics. Made from galvanized metal with a powder-coated finish. The removable rose sprinkler allows for both gentle watering and direct pouring.",
    price: 1099,
    category: "accessories",
    colors: ["Sage Green", "Cream", "Charcoal"],
    sizes: ["1.5L", "2.5L"],
    stock: 55,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.7,
    reviews_count: 92,
    featured: false,
    additional_info: {
      material: "Galvanized Metal",
      capacity: "1.5L or 2.5L",
      features: "Removable rose sprinkler",
      indoor_outdoor: "Both",
      rust_resistant: true,
    },
  },
  {
    id: 13,
    name: "Fiddle Leaf Fig",
    slug: "fiddle-leaf-fig",
    description:
      "Elegant fiddle leaf fig with large, violin-shaped leaves. A statement plant for modern homes.",
    long_description:
      "The Fiddle Leaf Fig is a designer favorite, known for its dramatic, sculptural appearance. Native to West Africa, it thrives in bright, indirect light and adds instant sophistication to any room. Requires regular care and attention.",
    price: 3499,
    category: "plants",
    colors: ["Green"],
    sizes: ["Medium", "Large", "XL"],
    stock: 15,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.6,
    reviews_count: 87,
    featured: true,
    additional_info: {
      light: "Bright, indirect light",
      water: "Water weekly, allow top soil to dry",
      temperature: "18-24°C",
      humidity: "Medium",
      pet_friendly: false,
    },
  },
  {
    id: 14,
    name: "Succulent Mix Seeds",
    slug: "succulent-mix-seeds",
    description:
      "Assorted succulent seeds for creating your own succulent garden. Pack of 200 seeds.",
    long_description:
      "This diverse mix of succulent seeds includes various species perfect for beginners and enthusiasts alike. Easy to grow and maintain, these succulents are ideal for small spaces, terrariums, and dish gardens.",
    price: 399,
    category: "seeds",
    colors: ["N/A"],
    sizes: ["200 Seeds"],
    stock: 120,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.4,
    reviews_count: 63,
    featured: false,
    additional_info: {
      germination_time: "10-21 days",
      planting_depth: "Surface sow",
      temperature: "21-24°C",
      varieties_included: "8-10 different species",
      organic: false,
    },
  },
  {
    id: 15,
    name: "Moisture Meter - 3-in-1",
    slug: "moisture-meter-3-in-1",
    description:
      "Digital soil tester for moisture, pH, and light levels. Essential tool for plant care.",
    long_description:
      "Take the guesswork out of plant care with this accurate 3-in-1 meter. Easily test soil moisture, pH levels, and light intensity. No batteries required. Perfect for both indoor and outdoor gardening.",
    price: 599,
    category: "accessories",
    colors: ["Green"],
    sizes: ["Standard"],
    stock: 90,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.8,
    reviews_count: 156,
    featured: false,
    additional_info: {
      measurements: "Moisture, pH (3-8), Light",
      probe_length: "20cm",
      batteries_required: false,
      suitable_for: "Indoor and outdoor plants",
      accuracy: "High",
    },
  },
];

// Category information
export const categories = [
  {
    slug: "plants",
    name: "Plants",
    description:
      "Bring nature indoors with our curated collection of healthy, vibrant plants",
    icon: "🌿",
  },
  {
    slug: "seeds",
    name: "Seeds",
    description:
      "Premium quality seeds for your garden - vegetables, herbs, and flowers",
    icon: "🌱",
  },
  {
    slug: "planters",
    name: "Planters",
    description:
      "Beautiful planters and pots to complement your green companions",
    icon: "🪴",
  },
  {
    slug: "plant-care",
    name: "Plant Care",
    description: "Everything you need to keep your plants thriving and healthy",
    icon: "💚",
  },
  {
    slug: "decor",
    name: "Decor",
    description: "Elegant plant decor and displays to enhance your space",
    icon: "✨",
  },
  {
    slug: "accessories",
    name: "Accessories",
    description: "Essential tools and accessories for the modern gardener",
    icon: "🛠️",
  },
];
