// Sample products data - 15 products across 6 categories
export const sampleProducts = [
  {
    id: 1,
    name: "Monstera Deliciosa",
    slug: "monstera-deliciosa",
    description: [
      "Stunning tropical plant with large, glossy leaves",
      "Develops iconic natural splits as it matures",
      "Perfect for adding a bold statement to any space",
      "Easy to care for and fast-growing",
    ],
    price: 39900,
    price_range: "₹300-₹500", // For filter
    category: "plants",
    subcategory: "indoor-plants",
    type_of_plant: "Foliage Plant", // For filter
    maintenance: "Low", // For filter: Low, Medium, High
    availability: "In Stock", // For filter: In Stock, Out of Stock, Pre-Order
    color: ["Green"],
    size: ["Small", "Medium", "Large"],
    stock: 25,
    images: ["/1.png", "/2.png", "/3.png"],
    rating: 4.8,
    reviews_count: 124,
    featured: true,
    additional_info: {
      details:
        "The Monstera Deliciosa, also known as the Swiss Cheese Plant, is a popular choice for indoor gardening enthusiasts. Native to the rainforests of Central America, this plant thrives in bright, indirect light and moderate humidity. Its iconic split leaves make it a favorite for modern interior design.",
      light: "Bright, indirect light",
      water: "Water when top 2 inches of soil are dry",
      temperature: "18-27°C",
      humidity: "Medium to high",
      pet_friendly: false,
    },
    know_about:
      "Monstera Deliciosa is a species of flowering plant native to tropical forests of southern Mexico. It's known for its large, fenestrated leaves that develop splits and holes as the plant matures. This unique characteristic has made it one of the most sought-after houseplants globally. The plant can grow quite large indoors and produces aerial roots that help it climb in its natural habitat.",
    whats_in_box: [
      "1 Healthy Monstera Deliciosa Plant",
      "Grow bag or nursery pot",
      "Care instruction card",
      "Complimentary plant food sample",
    ],
  },
  {
    id: 2,
    name: "Snake Plant (Sansevieria)",
    slug: "snake-plant-sansevieria",
    description: [
      "Incredibly hardy and low-maintenance plant",
      "Striking upright variegated leaves",
      "Excellent air purifier certified by NASA",
      "Perfect for beginners and busy plant parents",
    ],
    price: 49900,
    price_range: "₹300-₹500",
    category: "plants",
    subcategory: "indoor-plants",
    type_of_plant: "Succulent",
    maintenance: "Low",
    availability: "In Stock",
    color: ["Green", "Yellow-Green"],
    size: ["Small", "Medium"],
    stock: 40,
    images: ["/4.png", "/5.png", "/6.png"],
    rating: 4.9,
    reviews_count: 201,
    featured: true,
    additional_info: {
      details:
        "The Snake Plant, also known as Mother-in-Law's Tongue, is one of the most resilient houseplants available. It can tolerate low light, irregular watering, and still thrive. NASA studies have shown it's excellent at removing toxins from the air.",
      light: "Low to bright, indirect light",
      water: "Water every 2-3 weeks",
      temperature: "15-29°C",
      humidity: "Low to medium",
      pet_friendly: false,
    },
    know_about:
      "Snake Plants are native to tropical West Africa and are extremely adaptable. They're known for their sword-like leaves with distinctive yellow or white edges. These plants are champions at converting CO2 to oxygen at night, making them ideal bedroom companions. They can survive weeks without water and tolerate a wide range of light conditions.",
    whats_in_box: [
      "1 Healthy Snake Plant",
      "Nursery pot with drainage",
      "Care guide with watering schedule",
      "Free decorative pebbles",
    ],
  },
  {
    id: 3,
    name: "Tomato Seeds - Heirloom Variety",
    slug: "tomato-seeds-heirloom",
    description: [
      "Premium heirloom tomato seeds",
      "Produces large, flavorful fruits",
      "100% Organic and non-GMO certified",
      "High germination rate guaranteed",
    ],
    price: 9900,
    price_range: "Under ₹100",
    category: "seeds",
    subcategory: "fruiting-seeds",
    type_of_plant: "Fruiting Plant",
    maintenance: "Medium",
    availability: "In Stock",
    color: ["N/A"],
    size: ["50 Seeds", "100 Seeds"],
    stock: 150,
    images: ["/7.jpg"],
    rating: 4.7,
    reviews_count: 89,
    featured: false,
    additional_info: {
      details:
        "These heirloom tomato seeds are carefully selected for superior taste and productivity. Perfect for home gardeners looking to grow authentic, flavorful tomatoes.",
      germination_time: "7-14 days",
      planting_depth: "0.5 cm",
      spacing: "60-90 cm",
      harvest_time: "60-80 days",
      organic: true,
    },
    know_about:
      "Heirloom tomatoes are open-pollinated varieties that have been passed down through generations. Unlike hybrid varieties, these seeds will produce plants identical to their parent, preserving traditional flavors and characteristics. They offer superior taste with rich, complex flavors that modern hybrids often lack.",
    whats_in_box: [
      "50 or 100 premium heirloom tomato seeds",
      "Sealed moisture-proof packet",
      "Complete growing guide",
      "Germination tips card",
    ],
  },
  {
    id: 4,
    name: "Basil Seeds - Sweet Genovese",
    slug: "basil-seeds-sweet-genovese",
    description: [
      "Aromatic sweet basil seeds for culinary use",
      "Classic Italian Genovese variety",
      "Easy to grow indoors or outdoors",
      "Fast germination in 5-10 days",
    ],
    price: 10900,
    price_range: "₹100-₹200",
    category: "seeds",
    subcategory: "microgreens-herbs",
    type_of_plant: "Herb",
    maintenance: "Low",
    availability: "In Stock",
    color: ["N/A"],
    size: ["100 Seeds", "250 Seeds"],
    stock: 200,
    images: ["/8.png"],
    rating: 4.6,
    reviews_count: 156,
    featured: false,
    additional_info: {
      details:
        "Sweet Genovese Basil is the classic Italian basil variety, perfect for pesto, salads, and Italian dishes. These seeds are easy to germinate and grow quickly, providing fresh herbs for your kitchen.",
      germination_time: "5-10 days",
      planting_depth: "0.25 cm",
      spacing: "15-30 cm",
      harvest_time: "30-40 days",
      organic: true,
    },
    know_about:
      "Sweet Genovese Basil is the most popular basil variety worldwide, prized for its large, tender leaves and intense aromatic flavor. It's the traditional basil used in Italian cuisine, especially for making authentic pesto. Rich in antioxidants and essential oils, it also has natural antibacterial properties.",
    whats_in_box: [
      "100 or 250 organic basil seeds",
      "Airtight resealable packet",
      "Step-by-step growing instructions",
      "Harvest and usage tips",
    ],
  },
  {
    id: 5,
    name: "Ceramic Planter - Modern White",
    slug: "ceramic-planter-modern-white",
    description: [
      "Elegant ceramic planter with drainage hole",
      "Handcrafted with smooth matte finish",
      "Modern minimalist geometric design",
      "Includes matching saucer",
    ],
    price: 1299,
    price_range: "Under ₹100",
    category: "planters",
    subcategory: "ceramic",
    type_of_plant: "N/A",
    maintenance: "N/A",
    availability: "In Stock",
    color: ["White", "Grey", "Black"],
    size: ["Small (4 inch)", "Medium (6 inch)", "Large (8 inch)"],
    stock: 60,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.8,
    reviews_count: 98,
    featured: true,
    additional_info: {
      details:
        "This handcrafted ceramic planter features a smooth matte finish and modern geometric design. The included drainage hole ensures proper water management.",
      material: "Ceramic",
      drainage: "Yes",
      saucer_included: true,
      indoor_outdoor: "Indoor",
      weight: "500g - 1.2kg (varies by size)",
    },
    know_about:
      "Ceramic planters are excellent for maintaining consistent soil moisture and temperature. The porous nature of high-quality ceramic allows for air circulation to plant roots while the glazed finish adds aesthetic appeal. These planters are fired at high temperatures for durability and are perfect for showcasing your favorite plants.",
    whats_in_box: [
      "1 Ceramic planter",
      "Matching drainage saucer",
      "Protective cork pads",
      "Care instructions",
    ],
  },
  {
    id: 6,
    name: "Terracotta Pot Set",
    slug: "terracotta-pot-set",
    description: [
      "Classic terracotta pots set of 3",
      "Natural clay for healthy plant growth",
      "Breathable material allows air circulation",
      "Suitable for indoor and outdoor use",
    ],
    price: 799,
    price_range: "Under ₹100",
    category: "planters",
    subcategory: "terracotta",
    type_of_plant: "N/A",
    maintenance: "N/A",
    availability: "In Stock",
    color: ["Terracotta"],
    size: ['Set of 3 (4", 6", 8")'],
    stock: 35,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.5,
    reviews_count: 67,
    featured: false,
    additional_info: {
      details:
        "Traditional terracotta pots are ideal for plant health as they allow air and water to pass through the walls. This set includes three different sizes for various plant types.",
      material: "Natural Clay",
      drainage: "Yes",
      saucer_included: false,
      indoor_outdoor: "Both",
      sizes_included: "4 inch, 6 inch, 8 inch",
    },
    know_about:
      "Terracotta has been used for plant containers for thousands of years. Made from natural clay, these pots are porous and allow excellent air and water exchange, preventing root rot. The earthy color and rustic charm make them timeless favorites. They develop a beautiful patina over time as minerals from water create natural weathering.",
    whats_in_box: [
      '3 Terracotta pots (4", 6", 8")',
      "Each pot with drainage hole",
      "Care and maintenance guide",
      "Seasoning instructions",
    ],
  },
  {
    id: 7,
    name: "Organic Potting Mix - Premium Blend",
    slug: "organic-potting-mix-premium",
    description: [
      "Nutrient-rich organic potting soil",
      "Perfect for indoor and outdoor plants",
      "Excellent drainage with moisture retention",
      "pH balanced for optimal growth",
    ],
    price: 449,
    price_range: "Under ₹100",
    category: "plant-care",
    subcategory: "potting-mix-fertilizers",
    type_of_plant: "N/A",
    maintenance: "N/A",
    availability: "In Stock",
    color: ["N/A"],
    size: ["5kg", "10kg", "20kg"],
    stock: 100,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.9,
    reviews_count: 234,
    featured: true,
    additional_info: {
      details:
        "Our premium potting mix is specially formulated with coco peat, vermicompost, perlite, and organic nutrients. Provides excellent drainage while retaining moisture.",
      composition: "Coco Peat, Vermicompost, Perlite, Neem Cake",
      ph_level: "6.0-6.5",
      organic: true,
      suitable_for: "All plant types",
      shelf_life: "12 months",
    },
    know_about:
      "This premium blend combines the best organic components for plant health. Coco peat provides excellent water retention, vermicompost adds rich nutrients, perlite ensures proper aeration, and neem cake acts as a natural pest deterrent. The mix is sterilized and free from harmful pathogens, making it safe for all plants.",
    whats_in_box: [
      "5kg, 10kg or 20kg organic potting mix",
      "Resealable moisture-proof bag",
      "Usage instructions",
      "Mixing ratio guide for different plants",
    ],
  },
  {
    id: 8,
    name: "Liquid Plant Food - All Purpose",
    slug: "liquid-plant-food-all-purpose",
    description: [
      "Complete liquid fertilizer NPK 10-10-10",
      "Promotes vigorous growth and blooms",
      "Easy to use - just dilute with water",
      "Suitable for all indoor and outdoor plants",
    ],
    price: 349,
    price_range: "Under ₹100",
    category: "plant-care",
    subcategory: "potting-mix-fertilizers",
    type_of_plant: "N/A",
    maintenance: "N/A",
    availability: "In Stock",
    color: ["N/A"],
    size: ["500ml", "1L"],
    stock: 80,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.7,
    reviews_count: 145,
    featured: false,
    additional_info: {
      details:
        "This all-purpose liquid plant food provides essential nutrients for vigorous growth, lush foliage, and abundant blooms. Easy to use and quickly absorbed by plants.",
      npk_ratio: "10-10-10",
      dilution_ratio: "5ml per liter of water",
      frequency: "Every 2 weeks during growing season",
      organic: false,
      shelf_life: "24 months",
    },
    know_about:
      "NPK 10-10-10 is a balanced fertilizer formula providing equal parts nitrogen (for foliage), phosphorus (for roots and flowers), and potassium (for overall plant health). Liquid fertilizers are immediately available to plants as they're already dissolved, making them ideal for quick nutrient uptake and visible results within days.",
    whats_in_box: [
      "500ml or 1L liquid plant food concentrate",
      "Leak-proof bottle with measuring cap",
      "Detailed dilution chart",
      "Application schedule guide",
    ],
  },
  {
    id: 9,
    name: "Macrame Plant Hanger",
    slug: "macrame-plant-hanger",
    description: [
      "Handwoven macrame plant hanger",
      "Made from 100% natural cotton rope",
      "Features intricate knotwork design",
      "Perfect for creating vertical gardens",
    ],
    price: 699,
    price_range: "Under ₹100",
    category: "decor",
    subcategory: "garden-decor",
    type_of_plant: "N/A",
    maintenance: "N/A",
    availability: "In Stock",
    color: ["Natural", "Black", "Cream"],
    size: ["36 inch", "48 inch"],
    stock: 45,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.8,
    reviews_count: 112,
    featured: false,
    additional_info: {
      details:
        "This beautiful macrame plant hanger is handcrafted from 100% natural cotton rope. Can hold pots up to 8 inches in diameter and adds bohemian charm to any space.",
      material: "100% Cotton Rope",
      max_pot_diameter: "8 inches",
      weight_capacity: "5 kg",
      installation: "Ceiling hook included",
      handmade: true,
    },
    know_about:
      "Macrame is an ancient textile art form that has experienced a modern revival. These plant hangers are handcrafted by skilled artisans using traditional knotting techniques. The natural cotton rope is strong, durable, and develops a soft patina over time. Perfect for adding vertical interest to your plant display while saving floor space.",
    whats_in_box: [
      "1 Handmade macrame plant hanger",
      "Ceiling hook and hardware",
      "Installation instructions",
      "Weight capacity guidelines",
    ],
  },
  {
    id: 10,
    name: "Plant Stand - Bamboo",
    slug: "plant-stand-bamboo",
    description: [
      "Sustainable bamboo plant stand with 3 tiers",
      "Eco-friendly and naturally water-resistant",
      "Elegant display for multiple plants",
      "Easy assembly with included hardware",
    ],
    price: 1899,
    price_range: "Under ₹100",
    category: "decor",
    subcategory: "garden-decor",
    type_of_plant: "N/A",
    maintenance: "N/A",
    availability: "In Stock",
    color: ["Natural Bamboo"],
    size: ["3 Tier (80cm H)"],
    stock: 20,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.6,
    reviews_count: 78,
    featured: true,
    additional_info: {
      details:
        "This eco-friendly bamboo plant stand features three spacious shelves perfect for creating a stunning plant display. Made from sustainable bamboo with a natural finish.",
      material: "Sustainable Bamboo",
      dimensions: "80cm H x 60cm W x 25cm D",
      weight_capacity: "15 kg total",
      assembly_required: true,
      eco_friendly: true,
    },
    know_about:
      "Bamboo is one of the most sustainable materials on Earth, growing up to 3 feet per day and requiring no pesticides. It's naturally water-resistant and stronger than many hardwoods. This stand showcases bamboo's beautiful grain patterns while providing a stable, stylish display for your plant collection.",
    whats_in_box: [
      "1 Bamboo plant stand (unassembled)",
      "All assembly hardware and tools",
      "Step-by-step assembly guide",
      "Protective floor pads",
    ],
  },
  {
    id: 11,
    name: "Pruning Shears - Professional",
    slug: "pruning-shears-professional",
    description: [
      "Professional-grade stainless steel blades",
      "Ergonomic non-slip rubberized grip",
      "Perfect for precise, clean cuts",
      "Cuts branches up to 20mm diameter",
    ],
    price: 899,
    price_range: "Under ₹100",
    category: "plant-care",
    subcategory: "garden-tools",
    type_of_plant: "N/A",
    maintenance: "N/A",
    availability: "In Stock",
    color: ["Green/Silver", "Black/Silver"],
    size: ["8 inch"],
    stock: 70,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.9,
    reviews_count: 189,
    featured: false,
    additional_info: {
      details:
        "These professional-grade pruning shears feature ultra-sharp stainless steel blades that stay sharp longer. The ergonomic design reduces hand fatigue during extended use.",
      blade_material: "Stainless Steel",
      handle_material: "Rubberized Grip",
      cutting_capacity: "Up to 20mm diameter",
      warranty: "1 year",
      includes: "Safety lock, cleaning cloth",
    },
    know_about:
      "Professional pruning shears are essential for maintaining plant health. Clean, precise cuts promote faster healing and prevent disease. The bypass cutting mechanism (like scissors) is ideal for live plants, creating smooth cuts that heal quickly. Stainless steel blades resist rust and stay sharp through hundreds of cuts.",
    whats_in_box: [
      "1 Professional pruning shears",
      "Safety lock mechanism",
      "Microfiber cleaning cloth",
      "Blade maintenance guide",
    ],
  },
  {
    id: 12,
    name: "Watering Can - Vintage Style",
    slug: "watering-can-vintage-style",
    description: [
      "Charming vintage-style metal watering can",
      "Galvanized metal with powder-coated finish",
      "Removable rose sprinkler included",
      "Rust-resistant for long-lasting use",
    ],
    price: 1099,
    price_range: "₹100-₹200",
    category: "plant-care",
    subcategory: "watering-tools",
    type_of_plant: "N/A",
    maintenance: "N/A",
    availability: "In Stock",
    color: ["Sage Green", "Cream", "Charcoal"],
    size: ["1.5L", "2.5L"],
    stock: 55,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.7,
    reviews_count: 92,
    featured: false,
    additional_info: {
      details:
        "This beautifully designed watering can combines functionality with vintage aesthetics. The removable rose sprinkler allows for both gentle watering and direct pouring.",
      material: "Galvanized Metal",
      capacity: "1.5L or 2.5L",
      features: "Removable rose sprinkler",
      indoor_outdoor: "Both",
      rust_resistant: true,
    },
    know_about:
      "Traditional watering cans with rose sprinklers distribute water gently, mimicking natural rainfall. This prevents soil displacement and protects delicate seedlings. Galvanized metal is naturally rust-resistant and develops a beautiful patina over time. The vintage design adds charm to your gardening routine while providing practical functionality.",
    whats_in_box: [
      "1 Vintage-style watering can",
      "Removable rose sprinkler head",
      "Care and maintenance tips",
      "Proper watering technique guide",
    ],
  },
  {
    id: 13,
    name: "Fiddle Leaf Fig",
    slug: "fiddle-leaf-fig",
    description: [
      "Elegant plant with large violin-shaped leaves",
      "Statement piece for modern interiors",
      "Native to West African rainforests",
      "Designer favorite for instant sophistication",
    ],
    price: 3499,
    price_range: "Above ₹500",
    category: "plants",
    subcategory: "indoor-plants",
    type_of_plant: "Foliage Plant",
    maintenance: "High",
    availability: "In Stock",
    color: ["Green"],
    size: ["Medium", "Large", "XL"],
    stock: 15,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.6,
    reviews_count: 87,
    featured: true,
    additional_info: {
      details:
        "The Fiddle Leaf Fig is a designer favorite, known for its dramatic, sculptural appearance. It thrives in bright, indirect light and adds instant sophistication to any room. Requires regular care and attention.",
      light: "Bright, indirect light",
      water: "Water weekly, allow top soil to dry",
      temperature: "18-24°C",
      humidity: "Medium",
      pet_friendly: false,
    },
    know_about:
      "Ficus lyrata, the Fiddle Leaf Fig, has become an icon of interior design in the 2010s and 2020s. Native to West African lowland tropical rainforests, it naturally grows as an epiphyte on other trees. Its large, deeply veined leaves can grow up to 18 inches long. While it has a reputation for being finicky, consistent care and avoiding location changes will keep it thriving.",
    whats_in_box: [
      "1 Premium Fiddle Leaf Fig",
      "Nursery pot or decorative planter",
      "Detailed care guide",
      "Leaf cleaning cloth",
    ],
  },
  {
    id: 14,
    name: "Succulent Mix Seeds",
    slug: "succulent-mix-seeds",
    description: [
      "Assorted succulent seeds - 8-10 varieties",
      "Perfect for terrariums and dish gardens",
      "Easy to grow and low maintenance",
      "Ideal for beginners and enthusiasts",
    ],
    price: 399,
    price_range: "Under ₹100",
    category: "seeds",
    subcategory: "flowering-seeds",
    type_of_plant: "Succulent",
    maintenance: "Low",
    availability: "In Stock",
    color: ["N/A"],
    size: ["200 Seeds"],
    stock: 120,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.4,
    reviews_count: 63,
    featured: false,
    additional_info: {
      details:
        "This diverse mix of succulent seeds includes various species perfect for beginners and enthusiasts alike. Easy to grow and maintain, these succulents are ideal for small spaces.",
      germination_time: "10-21 days",
      planting_depth: "Surface sow",
      temperature: "21-24°C",
      varieties_included: "8-10 different species",
      organic: false,
    },
    know_about:
      "Succulents are incredibly diverse plants that store water in their leaves, stems, or roots, allowing them to survive in arid conditions. They come in countless shapes, colors, and textures. Growing from seed requires patience but is incredibly rewarding, as you'll witness the entire life cycle of these fascinating plants.",
    whats_in_box: [
      "200 mixed succulent seeds",
      "Species identification guide",
      "Germination instructions",
      "Succulent care basics card",
    ],
  },
  {
    id: 15,
    name: "Moisture Meter - 3-in-1",
    slug: "moisture-meter-3-in-1",
    description: [
      "3-in-1 soil tester - moisture, pH, light",
      "Take the guesswork out of plant care",
      "No batteries required - eco-friendly",
      "Perfect for indoor and outdoor plants",
    ],
    price: 599,
    price_range: "Under ₹100",
    category: "plant-care",
    subcategory: "garden-tools",
    type_of_plant: "N/A",
    maintenance: "N/A",
    availability: "In Stock",
    color: ["Green"],
    size: ["Standard"],
    stock: 90,
    images: ["/hero1.jpg", "/hero2.jpg", "/hero3.jpg"],
    rating: 4.8,
    reviews_count: 156,
    featured: false,
    additional_info: {
      details:
        "Take the guesswork out of plant care with this accurate 3-in-1 meter. Easily test soil moisture, pH levels, and light intensity for optimal plant health.",
      measurements: "Moisture, pH (3-8), Light",
      probe_length: "20cm",
      batteries_required: false,
      suitable_for: "Indoor and outdoor plants",
      accuracy: "High",
    },
    know_about:
      "Professional growers rely on soil meters to maintain optimal growing conditions. This 3-in-1 meter helps prevent over/under-watering (the #1 cause of plant death), ensures proper pH for nutrient absorption, and confirms adequate light levels. The analog design requires no batteries and provides instant, reliable readings.",
    whats_in_box: [
      "1 Three-in-one soil meter",
      "User manual with plant care charts",
      "Probe cleaning brush",
      "Optimal range guide for common plants",
    ],
  },
];

// Category information with subcategories
export const categories = [
  {
    slug: "plants",
    name: "Plants",
    description:
      "Bring nature indoors with our curated collection of healthy, vibrant plants",
    icon: "🌿",
    image: "/Plants.jpg",
    subcategories: [
      { slug: "indoor-plants", name: "Indoor Plants" },
      { slug: "flowering-plants", name: "Flowering Plants" },
      { slug: "fruiting-plants", name: "Fruiting Plants" },
      { slug: "air-plants", name: "Air Plants" },
      { slug: "foliage-plants", name: "Foliage Plants" },
      { slug: "outdoor-plants", name: "Outdoor Plants" },
      { slug: "aquatic-plants", name: "Aquatic Plants" },
      { slug: "medicinal-herbs-plants", name: "Medicinal & Herbs Plants" },
      { slug: "hanging-plants", name: "Hanging Plants" },
      { slug: "winter-plants", name: "Winter Plants" },
      { slug: "succulents-plants", name: "Succulents Plants" },
      { slug: "cactus-plants", name: "Cactus Plants" },
      { slug: "terrarium-plants", name: "Terrarium Plants" },
      { slug: "creepers-climbers-plants", name: "Creepers & Climbers Plants" },
    ],
  },
  {
    slug: "seeds",
    name: "Seeds",
    description:
      "Premium quality seeds for your garden - vegetables, herbs, and flowers",
    icon: "🌱",
    image: "/seeds.jpg",
    subcategories: [
      { slug: "fruiting-seeds", name: "Fruiting Seeds" },
      { slug: "vegetable-seeds", name: "Vegetable Seeds" },
      { slug: "flowering-seeds", name: "Flowering Seeds" },
      { slug: "microgreens-herbs", name: "Microgreens & Herbs" },
    ],
  },
  {
    slug: "planters",
    name: "Planters",
    description:
      "Beautiful planters and pots to complement your green companions",
    icon: "🪴",
    image: "/Pots.jpg",
    subcategories: [
      { slug: "ceramic", name: "Ceramic Planter" },
      { slug: "plastic", name: "Plastic Planter" },
      { slug: "recycled", name: "Recycled Planter" },
      { slug: "terracotta", name: "Terracotta Planter" },
      { slug: "seedling", name: "Seedling Planter" },
      { slug: "growbag", name: "Growbag" },
      { slug: "eco-friendly", name: "Eco Friendly Planter" },
    ],
  },
  {
    slug: "plant-care",
    name: "Plant Care",
    description: "Everything you need to keep your plants thriving and healthy",
    icon: "💚",
    image: "/Plant care.jpg",
    subcategories: [
      {
        slug: "potting-mix-fertilizers",
        name: "Potting Mix & Organic Fertilizers",
      },
      { slug: "pest-control", name: "Pest Control" },
      { slug: "garden-tools", name: "Garden Tools" },
      { slug: "watering-tools", name: "Watering Tools" },
      { slug: "plant-stand", name: "Plant Stand" },
      { slug: "plant-doctor", name: "Plant Doctor - Consultant" },
    ],
  },
  {
    slug: "decor",
    name: "Decor",
    description: "Elegant plant decor and displays to enhance your space",
    icon: "✨",
    image: "/Decor.jpg",
    subcategories: [
      { slug: "moss-wall", name: "Moss Wall" },
      { slug: "terrarium", name: "Terrarium" },
      { slug: "terrarium-biocrew", name: "Terrarium Biocrew" },
      { slug: "kokedama", name: "Kokedama" },
      { slug: "garden-decor", name: "Garden Decor" },
    ],
  },
  {
    slug: "accessories",
    name: "Accessories",
    description: "Essential tools and accessories for the modern gardener",
    icon: "🛠️",
    image: "/Plant tools.jpg",
    subcategories: [
      { slug: "organic-soap", name: "Organic Soap" },
      { slug: "s-curve-toothbrush", name: "S Curve Toothbrush" },
      { slug: "flat-loofah", name: "Flat Loofah" },
      { slug: "regular-neem-comb", name: "Regular Neem Comb" },
      { slug: "seed-paper-pen", name: "Seed Paper Pen" },
    ],
  },
];
